### ISSUE TITLE
Internal error on command:"MMU_CHANGE_TOOL"

### ISSUE THREAD

**Issue by dominikacri** [moggieuk/Happy-Hare#202]
Get reproducable an exception everytime calling T1 (Tx)  command. 

Internal error on command:"T1"
Internal Error on WebRequest: gcode/script
Traceback (most recent call last):
  File "/home/dominik/klipper/klippy/extras/mmu.py", line 4614, in _wrap_sync_extruder_to_gear
    yield self
  File "/home/dominik/klipper/klippy/extras/mmu.py", line 4379, in _trace_filament_move
    trig_pos = hmove.homing_move(pos, speed, probe_pos=True, triggered=homing_move > 0, check_triggered=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dominik/klipper/klippy/extras/homing.py", line 94, in homing_move

Hardware
ERCF2
Easy ERCF Board (SAMD)
SKR Octopus Pro 

No CANBus, boards connected via USB

Default toolhead_extruder_to_nozzle and toolhead_sensor_to_nozzle values. 

[klippy.log](https://github.com/moggieuk/Happy-Hare/files/14395922/klippy.log)
[mmu_config.zip](https://github.com/moggieuk/Happy-Hare/files/14395923/mmu_config.zip)

**Comment by moggieuk** [comment]
Thanks. Looking...

**Comment by moggieuk** [comment]
Ok. This can happen when the mismatch in "step movement distance" is too great between extruder stepper and gear stepper.

Try one of these three:
1. reduce the microsteps on your extruder - 128 is extremely fine given the 50:10 gear ratio and frankly will reduce torque.  Try 64.
2. Increase the steps on your MMU gear stepper from 16 to 32.
3. Do both of the above.

Let me know.

**Comment by dominikacri** [comment]
Top, works now like a charm ! 
Reduced to 32 extruder microsteps which is already more than needed. 
Thanks a lot for your work.

**Comment by bartoszwas** [comment]
Had same issue. Weird thing is that my machine was running perfectly for 2-3 months and then suddenly this error... I thought its klipper issue so I did updates on all mcus but didn't help..

Increasing MMU Gear steps to 32 seems to fix it. Extruder (EBB 2209 CAN) was already on 32 steps.
