### ISSUE TITLE
[mmu_server] Preprocessor throwing errors

### ISSUE THREAD

**Issue by PatrikTheDev** [moggieuk/Happy-Hare#55]
I just updated to the latest HH version and enabled the preprocessor. Moonraker seems to have issues starting it though, this is in the logs:

```
2023-09-23 11:10:00,578 [server.py:load_component()] - Unable to load component: (mmu_server)
Traceback (most recent call last):
  File "/home/patrikthedev/moonraker/moonraker/server.py", line 269, in load_component
    module = importlib.import_module(full_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'moonraker.components.mmu_server'
```

Did the moonraker updater not install some files/dependencies?

**Comment by moggieuk** [comment]
Did you run `./install.sh` after upgrading as per the announcement?  Sounds like the symlinks to the moonraker module are missing and those are set up with the install.sh script.

**Comment by PatrikTheDev** [comment]
Shouldn't Moonraker run that on its own?
<img width="522" alt="image" src="https://github.com/moggieuk/Happy-Hare/assets/25883885/04b48aaf-f6ce-4c80-a24f-183d94b466f5">

**Comment by moggieuk** [comment]
No it doesn't for security reasons .. it's very confusing (confused me) but it only reads that script for dependency checking.
I wish it would run it!    Unless I'm missing something on moonraker config -- if you can make it work let me know!
