### ISSUE TITLE
Error on toolchange after most recent update

### ISSUE THREAD

**Issue by iamnotahippy** [moggieuk/Happy-Hare#553]
After the 12/12/2024 update, I'm getting the following error after the filament has homed to the toolhead:
```
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 309, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 470, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 110, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/pi/klipper/klippy/gcode.py", line 325, in run_script_from_command
    self._process_commands(script.split("\n"), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 309, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 220, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/klipper/klippy/extras/mmu/mmu.py", line 6110, in cmd_MMU_CHANGE_TOOL
    self._select_and_load_tool(tool)
  File "/home/pi/klipper/klippy/extras/mmu/mmu.py", line 5588, in _select_and_load_tool
    self.load_sequence()
  File "/home/pi/klipper/klippy/extras/mmu/mmu.py", line 4660, in load_sequence
    hm = self._home_to_extruder(self.extruder_homing_max)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/klipper/klippy/extras/mmu/mmu.py", line 4279, in _home_to_extruder
    actual,homed,measured,_ = self._home_to_extruder_collision_detection(max_length)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/klipper/klippy/extras/mmu/mmu.py", line 4320, in _home_to_extruder_collision_detection
    with self._wrap_gear_current(self.extruder_collision_homing_current, "for collision detection"):
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/pi/klipper/klippy/extras/mmu/mmu.py", line 5416, in _wrap_gear_current
    self._adjust_gear_current(percent, reason)
  File "/home/pi/klipper/klippy/extras/mmu/mmu.py", line 5396, in _adjust_gear_current
    if self.gear_tmc and 0 < percent < 200 and percent != self.gear_percentage_run_current:
                         ^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by milkmother69** [comment]
I got the same error, fixed it by reverting to commit 271af7c.
Seems like there was a bunch of changes involving the gear stepper recently, probably a mistake in there somewhere.

**Comment by Sparkss** [comment]
> I got the same error, fixed it by reverting to commit [271af7c](https://github.com/moggieuk/Happy-Hare/commit/271af7ccf8adb5ad296b891fd7cf6e6e8dae4de4). Seems like there was a bunch of changes involving the gear stepper recently, probably a mistake in there somewhere.

Same issue here. Now to try to remember how to revert to a previous commit with git :).

**Comment by moggieuk** [comment]
looking...

**Comment by moggieuk** [comment]
FIXED.  Just force an update with `update-manager` in Mainsail, etc. (i.e. you might have to hit the refresh button to see the update)

**Comment by iamnotahippy** [comment]
Confirmed fixed.
