### ISSUE TITLE
Error importing file_manager during tests.

### ISSUE THREAD

**Issue by rnlahaye** [moggieuk/Happy-Hare#560]
When trying to run the unit tests (via `test/runner.sh`), I get the following error:

```
Traceback (most recent call last):
  File "/home/rynildredeth/Happy-Hare/test/components/test_mmu_server.py", line 13, in setUp
    self.subject = MmuServer(MagicMock())
  File "/home/rynildredeth/Happy-Hare/components/mmu_server.py", line 80, in __init__
    self.setup_placeholder_processor(config)
  File "/home/rynildredeth/Happy-Hare/components/mmu_server.py", line 736, in setup_placeholder_processor
    from .file_manager import file_manager
ModuleNotFoundError: No module named 'components.file_manager'
```

This error occurs both on my laptop and when ssh-ed into the printer.

**Comment by moggieuk** [comment]
I'm away from my printer / system, but I believe you need to `cd` into the `components/file_manager` or at least the `components` directory under moonraker for this to work because that is where `mmu_server.py` will normally be loaded by moonraker.
